vim.keymap.set({'n'}, "<leader>ga", function ()
  vim.api.nvim_command("G add %")
end)
vim.keymap.set({'n'}, "<leader>gu", function ()
  vim.api.nvim_command("G restore --staged %")
end)
vim.keymap.set({'n'}, "<leader>gb", function ()
  vim.api.nvim_command("G blame")
end)
